version: '3.8'

services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 reddit_clone:app
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PW=""
      - POSTGRES_DB=reddit
      - POSTGRES_HOST=docker.for.mac.localhost:5432
      - REDIS_HOST=myredisdb  # note this matches name below
      - REDIS_PORT=6379
      - REDIS_COMMENT_VOTES_DB=0
      - REDIS_POST_COMMENTS_DB=1
      - REDIS_CACHE_TTL_MS=86_400_000
    depends_on:
      - myredisdb

  myredisdb:
    image: redis:6-alpine
