version: '3.8'

services:
  tests:
    build:
      dockerfile: tests/Dockerfile
      context: .
    image: tests
    container_name: tests
    ports:
      - 8000:8000
    command: pytest
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PW=""
      - POSTGRES_DB=reddit_pytest
      - POSTGRES_HOST=docker.for.mac.localhost:5432
      - REDIS_HOST=myredispytestdb
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_CACHE_TTL_MS=86_400_000
    depends_on:
      - myredispytestdb

  myredispytestdb:
    ports:
      - 6379:6379
    image: redis:6-alpine
