"""removed title from comments

Revision ID: da6b9d9fef0f
Revises: 8dc647c9aca4
Create Date: 2021-09-07 14:53:47.640244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6b9d9fef0f'
down_revision = '8dc647c9aca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_title_key', 'comments', type_='unique')
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('comments_title_key', 'comments', ['title'])
    # ### end Alembic commands ###
