"""unique constraint on site name

Revision ID: f74a290ab2ba
Revises: da6b9d9fef0f
Create Date: 2021-09-08 14:23:02.346461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74a290ab2ba'
down_revision = 'da6b9d9fef0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sites_name', table_name='sites')
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.create_index('ix_sites_name', 'sites', ['name'], unique=False)
    # ### end Alembic commands ###
